agro_tracability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name='clients'


urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'),
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    
    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<int:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),
]

cooperatives/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from .views import (
    coop_dashboard,
    add_section,
    add_sous_section,
    export_parcelles_to_pdf,
    producteurs,
    # cooperative,
    prod_update,
    prod_delete,
    parcelles,
    parcelle_delete,
    # planting,
    # planting_update,
    formation,
    detail_formation,
    AddPlantingView,
    export_planting_xls,
    # use Ajax and jquery request
    my_section,
    export_producteur_csv,
    # PlantingDelete,
    export_prods_to_pdf,
    export_prod_xls,
    export_parcelle_xls,
    export_plant_xls, Editformation, parcelle_update, update_section, delete_section, export_section_xls,
    update_sous_section,
    export_sous_section_xls, export_formation_xls, delete_sous_section, ParcellesMapView, parcelle_list, ReceptionView,
    folium_map, PlantingList, detail_planting, coopdetailPlantings, CoopPlantings, getParcelleCoop, map_by_cooperative,
    # delete_sous_section, export_sous_section_xls, export_formation_xls, my_parcelles, ParcellesView,
    # load_section
)

app_name='cooperatives'

urlpatterns = [
    # Patient
    # path('cooperative/<int:id>', cooperative, name='cooperative'),
    path('producteur/<str:code>/modifier', prod_update, name='modifier'),
    path('producteur/<str:code>/supprimer', prod_delete, name='del_producteur'),
    # path('parcelle/<int:id>', parcelle_delete, name='del_parcelle'),
    path('parcelle/<int:id>/modifier', parcelle_update, name='edit_parcelle'),
    path('parcelle/<int:id>/supprimer', parcelle_delete, name='parcelle_delete'),
    path('section/<int:id>/modifier', update_section, name='update_section'),
    path('section/<int:id>/delete/supprimer', delete_section, name='delete_section'),
    path('sous_section/<int:id>/modifier', update_sous_section, name='update_sous_section'),
    path('sous_section/<int:id>/supprimer', delete_sous_section, name='delete_sous_section'),
    path('dashboard/', coop_dashboard, name='dashboard'),
    path('sections/', add_section, name='section'),
    path('sous_sections/', add_sous_section, name='sous_sections'),
    path('formation/', formation, name='formations'),
    path('Editformation/<int:id>', Editformation, name='Editformation'),
    path('formation/<int:id>', detail_formation, name='formation'),
    path('producteurs/', producteurs, name='producteurs'),
    path('parcelles/', parcelles, name='parcelles'),
    #path('my_parcelles/', my_parcelles, name='my_parcelles'),
    # path('plantings/', planting, name='planting'),
    path('planting_coop/', CoopPlantings, name='CoopPlantings'),
    path('coopdetailPlantings/', coopdetailPlantings, name='coopdetailPlantings'),
    path('plantings/<int:id>/', detail_planting, name='suivi_planting'),
    path('add_planting/', AddPlantingView.as_view(), name='add_planting'),
# detail_planting
    # path('planting/<int:pk>', PlantingDelete.as_view(), name='planting-delete'),
    path('folium_map/', folium_map, name='folium_map'),

    #get Ajax Data
    # path('parcelles/data', ParcellesView.as_view(), name="parcelles_data"),
    path('parcelle_list/', parcelle_list, name="parcelle_list"),
    path('parcelles_list/', ParcellesMapView.as_view(), name="parcelle_list"),

    #path('my-section/', my_section, name='my_section'),
    # path('ajax/load-section/', load_section, name='ajax_load_section'),

    #Exportation de Données En Excel
    # path('export/csv/', export_producteur_csv, name='export_producteur_csv'),
    path('producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    path('sections/xls/', export_section_xls, name='export_section_xls'),
    path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    path('plants/xls/', export_plant_xls, name='export_plant_xls'),
    path('formations/xls/', export_formation_xls, name='export_formation_xls'),
    path('plantings/xls/', export_planting_xls, name='export_planting_xls'),

    #Export Données EN PDF
    path('producteurs/pdf/', export_prods_to_pdf, name='export_prods_to_pdf'),
    path('parcelles/pdf/', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),


    path('parcelleCoop/<int:pk>/', getParcelleCoop, name="parcelleCoop"),

    #route des parcelles par cooperative
    path('map_by_cooperative', map_by_cooperative, name="map_by_cooperative"),
]

cooperatives/forms.py
from django import forms
from django.contrib.auth import get_user_model
#from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields, DateInput
from django.http import request
# from django_select2 import forms as s2forms
# from django_select2.forms import ModelSelect2Widget

# class CooperativeWidget(s2forms.ModelSelect2Widget):
#     search_fields = [
#         "sigle__icontains",
#         #"email__icontains",
#     ]
#
# class SectionWidget(s2forms.ModelSelect2Widget):
#     search_fields = [
#         "libelle__icontains",
#         #"email__icontains",
#     ]

from cooperatives.models import Cooperative, Producteur, Section, Sous_Section, Parcelle, Planting, Formation, \
    Detail_Formation, Monitoring
# from cooperatives.views import cooperative
from parametres.models import Region, Projet, Activite, Origine, Sous_Prefecture, Espece

User = get_user_model()
non_allowed_username = ["abc", "123", "admin1", "admin12"]

class UserForm(forms.ModelForm):
    last_name = forms.CharField(label="Nom")
    first_name = forms.CharField(label="Prénoms")
    username = forms.CharField(label="Nom d’utilisateur")
    email = forms.EmailField(label="Adresse électronique")
    password = forms.CharField(widget=forms.PasswordInput(attrs={"id": "password", "class": "form-control"}), label="Mot de Passe")

    class Meta:
        model=User
        fields=['last_name','first_name','username', 'email', 'password']

class CoopForm(forms.ModelForm):
    #this is the extrafield for linking patient and their assigend doctor
    #this will show dropdown __str__ method doctor model is shown on html so override it
    #to_field_name this will fetch corresponding value  user_id present in Doctor model and return it
    region=forms.ModelChoiceField(queryset=Region.objects.all(),empty_label="Région")
    projet=forms.ModelChoiceField(queryset=Projet.objects.all(),empty_label="Projet")
    activite=forms.ModelChoiceField(queryset=Activite.objects.all(),empty_label="Natures Activités")
    class Meta:
        model=Cooperative
        fields=[
            'region',
            'sigle',
            'activite',
            'projet',
            'contacts',
            'logo',
        ]

class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        widgets = {
            # "cooperative": CooperativeWidget,
            #"co_authors": CoAuthorsWidget,
        }
        fields = [
            'libelle',
            'responsable',
            'contacts',
        ]

class Sous_SectionForm(forms.ModelForm):
    class Meta:
        model = Sous_Section
        fields = [
            # 'section',
            'libelle',
            'responsable',
            'contacts',
        ]

class Edit_Sous_SectionForm(forms.ModelForm):
    class Meta:
        model = Sous_Section
        fields = [
            'section',
            'libelle',
            'responsable',
            'contacts',
        ]

class ProdForm(forms.ModelForm):
    # origine = forms.ModelChoiceField(queryset=Origine.objects.all(), empty_label="Origine")
    sous_prefecture = forms.ModelChoiceField(queryset=Sous_Prefecture.objects.all())
    # section = forms.ModelChoiceField(queryset=Section.objects.all().fil, empty_label="Section")
    sous_section = forms.ModelChoiceField(queryset=Sous_Section.objects.all(), empty_label="Sous Section", required=False)
    class Meta:
        model = Producteur
        fields = [
            'code',
            'origine',
            'sous_prefecture',
            'type_producteur',
            'nom',
            'dob',
            'genre',
            'contacts',
            'localite',
            # 'section',
            'sous_section',
            'nb_parcelle',
            'image',
            'type_document',
            'num_document',
            'document',
        ]

class EditProdForm(forms.ModelForm):
    origine = forms.ModelChoiceField(queryset=Origine.objects.all(), empty_label="Origine")
    sous_prefecture = forms.ModelChoiceField(queryset=Sous_Prefecture.objects.all())
    section = forms.ModelChoiceField(queryset=Section.objects.all(), empty_label="Section")
    sous_section = forms.ModelChoiceField(queryset=Sous_Section.objects.all(), empty_label="Sous Section", required=False)
    class Meta:
        model = Producteur
        fields = [
            'code',
            'origine',
            'sous_prefecture',
            'type_producteur',
            'nom',
            'dob',
            'genre',
            'contacts',
            'localite',
            'section',
            'sous_section',
            'nb_enfant',
            'nb_parcelle',
            'image',
            'type_document',
            'num_document',
            'document',
        ]
    def get_cooperative(self, request, *args, **kwargs):
        cooperative = Cooperative.objects.get(user_id=request.user.id)
        producteur_obj = Producteur.objects.filter(cooperative_id=cooperative)
        return producteur_obj

class ParcelleForm(forms.ModelForm):
    #this is the extrafield for linking patient and their assigend doctor
    #this will show dropdown __str__ method doctor model is shown on html so override it
    #to_field_name this will fetch corresponding value  user_id present in Doctor model and return it
    # projet = forms.ModelChoiceField(queryset=Projet.objects.all(), empty_label="Projet")
    # section = forms.ModelChoiceField(queryset=Section.objects.all(), empty_label="Section")
    # producteur = forms.ModelChoiceField(queryset=Producteur.objects.all(), empty_label="Propriétaires")
    # sous_section = forms.ModelChoiceField(queryset=Sous_Section.objects.all(), empty_label="Sous Section",required=False)

    class Meta:
        model=Parcelle
        fields=[
            'code',
            # 'producteur',
            # 'sous_section',
            'acquisition',
            'latitude',
            'longitude',
            'culture',
            'certification',
            'superficie'
        ]

    #producteur = AutoCompleteField('producteur')
    # def __init__(self, user=None, **kwargs):
    #     super(ParcelleForm, self).__init__(**kwargs)
    #     if user:
    #         cooperative = Cooperative.objects.get(user_id=user)
    #         self.fields['propietaire'].queryset = Parcelle.objects.filter(propietaire__cooperative_id=cooperative)
    #         self.fields['section'].queryset = Parcelle.objects.filter(section__cooperative_id=cooperative)
    #         # self.fields['sous_section']= Parcelle.objects.filter(section__cooperative_id=cooperative)

class EditParcelleForm(forms.ModelForm):

    class Meta:
        model=Parcelle
        fields=[
            'code',
            'producteur',
            # 'sous_section',
            'acquisition',
            'latitude',
            'longitude',
            'culture',
            'certification',
            'superficie'
        ]

class FormationForm(forms.ModelForm):

    class Meta:
        model=Formation
        fields=[
            'projet',
            'formateur',
            'libelle',
            'details',
            'observation',
            'debut',
            'fin',
        ]

class EditFormationForm(forms.ModelForm):

    class Meta:
        model=Formation
        fields=[
            'projet',
            'formateur',
            'libelle',
            'details',
            'observation',
            'debut',
            'fin',
        ]

class DetailFormation(forms.ModelForm):
    # participant = forms.ModelMultipleChoiceField(queryset=Producteur.objects.all(), empty_label="Producteurs",required=False)
    # participant = forms.ModelMultipleChoiceField(queryset=Producteur.objects.all())
    participant = forms.CheckboxSelectMultiple()

    class Meta:
        model = Detail_Formation
        fields = [
            # 'formation',
            'participant',
        ]
        # widgets = {
        #     'participant': forms.CheckboxSelectMultiple(),
        # }
        # widgets = {'participant': ModelSelect2Widget(
        #     queryset=Producteur.objects.all().distinct('participant'),
        #     search_fields=['participant_icontains']
        # )}

from django.forms import ModelForm, inlineformset_factory

from .models import Planting, DetailPlanting
# from .models import FamilyMember, Profile


class PlantingForm(ModelForm):
    class Meta:
        model = Planting
        fields = [
            # "parcelle",
            "nb_plant_exitant",
            "plant_recus",
            "campagne",
            "projet",
            "date",
        ]

class DetailPlantingForm(ModelForm):
    class Meta:
        model = DetailPlanting
        fields = [
            # "planting",
            "espece",
            "nb_plante",
        ]

DetailPlantingFormSet = inlineformset_factory(
    Planting, DetailPlanting, form=DetailPlantingForm, extra=1)


class MonitoringForm(ModelForm):
    class Meta:
        model = Monitoring
        fields = [
            # "planting",
            # "espece",
            "espece",
            "mort",
            "remplace",
            "date",
            "mature",
            # "observation"
        ]

cooperatives/templates/cooperatives/parcelle_delete.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% bootstrap_messages %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Parheto10">
        <title>Agro - Map | Traçability</title>
        {% include '_partials/css.html' %}
        {% include '_partials/js.html' %}
        <script>
            $(document).ready(function(){
                $("#DeleteParcelleModal").modal('show');
            });
        </script>
    </head>
    <body>
        <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="DeleteParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                {% if parcelle.code %}
                                    <i class="fa fa-trash fa-fw"></i>  SUPPRESSION PARCELLE {{ parcelle.code }} {{ parcelle.producteur }}
                                {% else %}
                                    <i class="fa fa-trash fa-fw"></i>  SUPPRESSION PARCELLE DE {{ parcelle.producteur }}
                                {% endif %}
{#                                <h4 class="modal-title" id="exampleModalLabel" style="font-weight:bold"> <i class="fa fa-close"></i> </h4>#}
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 text-center">
                                        {% if parcelle.code %}
                                            <p style="font-size: 22px; font-weight: bold">La Parcelle ({{ parcelle.code }}) - {{ parcelle.producteur.nom }} {{ parcelle.producteur.prenoms }} sera supprimer définitivement,<br /> voulez-vous continuer ?</p>
                                        {% else %}
                                            <p style="font-size: 22px; font-weight: bold">La Parcelle de {{ parcelle.producteur.nom }} {{ parcelle.producteur.prenoms }} sera supprimée définitivement,<br /> voulez-vous continuer ?</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" name="btnValider" value="Confirmer" id="btnValider" class="btn btn-primary" style="font-size:1.7vmin;" />
                                  <a href="{% url 'cooperatives:parcelles' %}" class="btn btn-danger" style="color: white">
                                       Annuler
                                  </a>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </body>
</html>

cooperatives/templates/cooperatives/section.html
<option value="">---------</option>
{% for section in coop_sections  %}
    <option value="{{ section.pk }}">{{ section.name }}</option>
{% endfor %}

cooperatives/templates/cooperatives/sous_sections.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
    Sous Sections |
{% endblock %}
{% block content %}
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% if user.is_authenticated %}
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'cooperatives:dashboard' %}">{{ cooperative.sigle }} / {{ cooperative.get_projet_values }}</a>
        </div>
    {% endif %}

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'cooperatives/coop_sidebar.html' %}
</nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Sous Sections</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        {% include '_partials/messages_display.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <a href="{% url 'cooperatives:export_sous_section_xls' %}" class="btn btn-success"><i class="fa fa-download fa-fw"></i>Exporter En Excel</a>
                                <a href="#" class="btn btn-danger"> <i class="fa fa-file-pdf-o fa-fw">  </i>Exporter En PDF</a>
                                <button type="button" class="btn btn-primary pull-right" style="font-size:1.8vmin" data-toggle="modal" data-target="#ParcelleModal" data-whatever="@mdo">
                                    Ajouter une Sous Section
                                </button>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body" style="font-size: 14px">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead class="text-center">
                                            <tr class="text-center">
                                                <th class="text-center">SECTION</th>
                                                <th class="text-center">LIBELLE</th>
                                                <th class="text-center">RESPONSABLE</th>
                                                <th class="text-center">CONTACTS</th>
                                                <th class="text-center">ACTIONS</th>
                                            </tr>
                                        </thead>
                                        <tbody class="text-center">
                                            {% for sous_section in sous_sections %}
                                                <tr class="odd gradeX">
                                                    <td class="center">{{ sous_section.section.libelle }}</td>
                                                    <td class="center">{{ sous_section.libelle }}</td>
                                                    <td class="center">{{ sous_section.responsable }}</td>
                                                    <td class="center">{{ sous_section.contacts }}</td>
                                                    <td>
                                                        <a href="{% url 'cooperatives:update_sous_section' sous_section.id %}" class="btn btn-primary">
                                                            <i class="fa fa-edit fa-fw"></i>
                                                        </a>
                                                        <a href="{% url 'cooperatives:delete_sous_section' sous_section.id %}" class="btn btn-danger">
                                                            <i class="fa fa-trash fa-fw"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-8 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->

            <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="ParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <i class="glyphicon glyphicon-plus" style="margin-bottom: 10px"></i> AJOUTER SOUS SECTION
                                    <button ID="btnAnnuler" type="button" data-dismiss="modal" class="btn btn-danger pull-right" style="font-size:1.8vmin; margin-top: -5px">
                                        <i class="fa fa-close"></i>
                                    </button>
                            </div>
                            <div class="panel-body">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="col-sm-12" style="margin-top: 25px">
                                            <div class="form-group">
                                                <label>SECTION</label>
                                                <input type="text" list="section" placeholder="Chercher une section..." class="form-control">
                                                <datalist id="section">
{#                                                    {% render_field parcelleForm.producteur.nom class="form-control" %}#}
                                                    {% for s in sections %}
                                                        <option value="{{ s.libelle }} - {{ s.contacts }}"></option>
                                                    {% endfor %}
                                                </datalist>
{#                                                {% render_field parcelleForm.producteur class="form-control" %}#}
{#                                                <select name="section" placeholder="SECTION" class="form-control" id="id_section">#}
{#                                                    {% for section in sections %}#}
{#                                                        <option value="{{ section.id }}">{{ section.libelle }}</option>#}
{#                                                    {% endfor %}#}
{#                                                </select>#}
                                            </div>
                                            <div class="form-group">
                                                <label>LIBELLE</label>
                                                {% render_field form.libelle class="form-control" %}
                                            </div>
                                            <div class="form-group">
                                                <label>RESPONSABLE</label>
                                                {% render_field form.responsable class="form-control" %}
                                            </div>
                                            <div class="form-group">
                                                <label>CONTACTS</label>
                                                {% render_field form.contacts class="form-control" %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-footer">
{#                                <Button ID="btnAnnuler" style="font-size:1.7vmin; width:100px" class="btn btn-default"  data-dismiss="modal" >Annuler</Button>#}
                                <input type="submit" name="btnValider" value="Valider" id="btnValider" class="btn btn-success btn-block" style="font-size:1.7vmin" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}