agro_tracability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name='clients'


urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'),
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    
    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<int:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),
]

clients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import time
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import datetime

from django.utils.safestring import mark_safe
from django_countries.fields import CountryField

ANNEES = []
for r in range(2019, (datetime.datetime.now().year+1)):
    ANNEES.append((r,r))

def upload_logo_site(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "logos/" + self.sigle + ".jpeg"

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sigle = models.CharField(max_length=500, verbose_name="NOM / SIGLE")
    contacts = models.CharField(max_length=50, verbose_name="CONTACTS")
    libelle = models.CharField(max_length=250, verbose_name="NOM")
    pays = CountryField(blank_label='(Préciser Le Pays)')
    adresse = models.CharField(max_length=250, verbose_name="ADRESSE", blank=True)
    telephone1 = models.CharField(max_length=50)
    telephone2 = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=120, blank=True, verbose_name="ADRESSE EMAIL")
    siteweb = models.CharField(max_length=120, blank=True, verbose_name="SITE WEB")
    logo = models.ImageField(verbose_name="Logo", upload_to=upload_logo_site, blank=True)
    objects = models.Manager()

    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.sigle = self.sigle.upper()
        self.libelle = self.libelle.upper()
        super(Client, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "CLIENTS"
        verbose_name = "client"

    def Logo(self):
        if self.logo:
            return mark_safe('<img src="%s" style="width: 60px; height:50px;" />' % self.logo.url)
        else:
            return "Aucun Logo"

    Logo.short_description = 'Logo'

clients/views.py
import os
from itertools import product
import datetime
import xlwt
from django.db.models import Count
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login as dj_login, get_user_model, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.staticfiles import finders
from django.core.mail import send_mail
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.template.loader import get_template
from django.urls import reverse
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# from twisted.words.protocols.jabber.jstrports import client
from xhtml2pdf import pisa

from .models import Client
from parametres.models import (
    Sous_Prefecture,
    Origine,
    Prime,
    Projet,
    Activite,
    Region,
    Campagne, Cooperative
)

from cooperatives.models import (
    Producteur,
    Parcelle,
    Planting,
    Section,
    Sous_Section, Formation, Detail_Formation, DetailPlanting
)

def client_index(request):
    cooperatives = Cooperative.objects.all()
    AllCooperatives = Cooperative.objects.all()
    nb_cooperatives = Cooperative.objects.all().count()
    nb_producteurs = Producteur.objects.all().count()
    prod_coop = Cooperative.objects.annotate(nb_producteur=Count('producteurs'))
    #section_cooperative = Cooperative.objects.annotate(nb_section=Count('sections'))
    section_coop = Cooperative.objects.annotate(nb_section=Count('sections'))
    nb_parcelles = Parcelle.objects.all().count()
    Superficie = Parcelle.objects.aggregate(total=Sum('superficie'))['total']
    Total_plant = Planting.objects.aggregate(total=Sum('plant_recus'))['total']

    context = {
        'cooperatives':cooperatives,
        'AllCooperatives':AllCooperatives,
        'nb_cooperatives': nb_cooperatives,
        'nb_producteurs': nb_producteurs,
        'nb_parcelles': nb_parcelles,
        'Superficie': Superficie,
        'Total_plant': Total_plant,
        'prod_coop': prod_coop,
        'section_coop': section_coop,
        #'section_cooperative': section_cooperative,
    }
    return render(request, 'clients/index.html', context)

def detail_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    # coop_nb_producteurs =
    section = Section.objects.filter(cooperative_id=cooperative)
    sous_sections = Sous_Section.objects.filter(section__cooperative_id=cooperative)
    # section_prod = Producteur.objects.all().filter(section_id__in=section).count()
    section_prod = Section.objects.annotate(nb_producteur=Count('producteurs'))    
    prod_section = Producteur.objects.filter(section_id__in=section).count()
    coop_nb_producteurs = Producteur.objects.filter(cooperative_id=cooperative).count()
    nb_formations = Formation.objects.filter(cooperative_id=cooperative).count()
    parcelles_section = Parcelle.objects.filter(producteur__section_id__in=section).count()
    # section_parcelle = Section.objects.annotate(nb_producteur=Count('producteurs.parcelles'))
    coop_nb_parcelles = Parcelle.objects.filter(producteur__section__cooperative_id=cooperative).count()
    coop_superficie = Parcelle.objects.filter(producteur__cooperative_id=cooperative).aggregate(total=Sum('superficie'))['total']
    section_superf = Parcelle.objects.filter(producteur__section_id__in=section).aggregate(total=Sum('superficie'))['total']
    # section_plating = Planting.objects.filter(parcelle__producteur__section_id__in=section).aggregate(total=Sum('plant_recus'))['total']
    # plantings = DetailPlanting.objects.values("espece__libelle").filter(planting__parcelle__producteur__cooperative_id=cooperative).annotate(plante=Sum('plant_recus'))
    coop_plants_total = DetailPlanting.objects.filter(planting__parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('nb_plante'))['total']

    context = {
        'cooperative': cooperative,
        'coop_nb_producteurs': coop_nb_producteurs,
        'coop_nb_parcelles': coop_nb_parcelles,
        'coop_superficie': coop_superficie,
        'nb_formations': nb_formations,
        'section': section,
        'sous_sections': sous_sections,
        'prod_section': prod_section,
        'section_prod': section_prod,
        # 'section_parcelle': section_parcelle,
        'parcelles_section': parcelles_section,
        'coop_plants_total': coop_plants_total,
        'section_superf': section_superf,        
        # 'labels': labels,
        # 'data': data,
    }
    return render(request, 'clients/Coop/cooperative.html', context)

def section_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    coop_sections = Section.objects.all().filter(cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_sections': coop_sections,
    }
    return render(request, 'clients/Coop/coop_sections.html', context)

def sous_section_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    coop_sous_sections = Sous_Section.objects.all().filter(section__cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_sous_sections': coop_sous_sections,
    }
    return render(request, 'clients/Coop/coop_sous_sections.html', context)

def prod_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    coop_producteurs = Producteur.objects.all().filter(cooperative_id=cooperative)
    # coop_parcelles = Parcelle.objects.all().filter(producteur__section__cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_producteurs': coop_producteurs,
    }
    return render(request, 'clients/Coop/coop_producteurs.html', context)

def parcelle_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    # coop_producteurs = Producteur.objects.all().filter(cooperative_id=cooperative)
    coop_parcelles = Parcelle.objects.all().filter(producteur__section__cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_parcelles' : coop_parcelles,
    }
    return render(request, 'clients/Coop/coop_parcelle.html', context)

def planting_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    coop_plants = DetailPlanting.objects.filter(planting__parcelle__producteur__cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_plants': coop_plants,
    }
    return render(request, 'clients/Coop/coop_plantings.html', context)

def projet(request):
    client = Client.objects.get(user_id=request.user.id)
    projets = Projet.objects.all().filter(client_id=client)
    context = {
        'client': client,
        'projets': projets,
    }
    return render(request, 'clients/projets.html', context)

def detail_proj(request, id=None):
    instance = get_object_or_404(Projet, id=id)
    # cooperatives = Cooperative.objects.filter(cooperative__projet__i).count()
    producteurs_proj = Producteur.objects.filter(cooperative__projet=instance).count()
    parcelles = Parcelle.objects.filter(producteur__cooperative__projet=instance)
    # parcelles = Planting.objects.all().filter(projet_id=instance)
    nb_parcelles_proj = Parcelle.objects.filter(producteur__cooperative__projet=instance).count()
    plants = DetailPlanting.objects.filter(planting__projet_id=instance).aggregate(total=Sum('nb_plante'))['total']
    #nb_plants_proj = Planting.objects.all().filter(projet_id = instance).count()
    superficie_proj = Parcelle.objects.filter(producteur__cooperative__projet=instance).aggregate(total=Sum('superficie'))['total']

    # print(superficie_proj)
    context = {
        'instance': instance,
        'parcelles': parcelles,
        # 'cooperatives': cooperatives,
        'plants':plants,
        # 'parcelles':plants,
        'nb_parcelles_proj':nb_parcelles_proj,
        #'nb_plants_proj':nb_plants_proj,
        #'plants':plants,
        'superficie_proj':superficie_proj,
        'producteurs_proj':producteurs_proj,
    }
    return render(request, 'clients/projet.html', context)

def formations(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    coop_formations = Formation.objects.all().filter(cooperative_id=cooperative)
    context = {
        'cooperative': cooperative,
        'coop_formations': coop_formations,
    }
    return render(request, 'clients/Coop/coop_formations.html', context)

def detail_formation(request, id=None, _id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    instance = get_object_or_404(Formation, id=_id)
    # instance = Formation.objects.all().filter(cooperative_id=cooperative)
    participants = Detail_Formation.objects.all().filter(formation_id=instance)
    # participants = Producteur.objects.all().filter(cooperative_id=cooperative)
    context = {
        'cooperative':cooperative,
        'instance':instance,
        'participants':participants,
        # 'detailFormation':detailFormation,
        # 'participants': participants,
    }
    return render(request, 'clients/Coop/detail_formation1.html', context)

def localisation(request):
    parcelles = Parcelle.objects.all()
    context = {
        'parcelles' : parcelles
    }
    return render(request, 'clients/carte.html', context)

def localisation_coop(request, id=None):
    cooperative = get_object_or_404(Cooperative, id=id)
    # coop_producteurs = Producteur.objects.all().filter(cooperative_id=cooperative)
    points_coop = Parcelle.objects.all().filter(producteur__section__cooperative_id=cooperative)
    context = {

clients/templates/clients/client_nav.html
{% load static %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'clients:dashboard' %}">PANNEAU D'ADMINISTRATION - {{ user.username }}</a>
        {% endif %}
    </div>

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'clients/client_sidebar.html' %}
</nav>

clients/templates/clients/client_sidebar.html
{% load static %}
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{% url 'clients:dashboard' %}" class="active"><i class="fa fa-dashboard fa-fw"></i> DASHBOARD</a>
            </li>
            <li>
{#                <a href="{% url 'clients:projets' %}" class="active"><i class="fa fa-dashboard fa-fw"></i> GESTION PROJETS</a>#}
            </li>
            <li>
                <a href="{% url 'catre_parcelles' %}" target="_blank"><i class="fa fa-map-marker fa-fw"></i> PARCELLES</a>
            </li>
            <li>
                {#                  <a href="#" target="_blank"><i class="fa fa-map-marker fa-fw"></i> PLANTINGS</a>#}
            </li>
        </ul>
    </div>
</div>

clients/templates/clients/projets.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{{ form.media.css }}
{{ form.media.js }}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
    Projets |
{% endblock %}
{% block content %}
    <div id="wrapper">
            <!-- Navigation -->
            {% include 'chocolatiers/client_nav.html' %}
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header"><i class="fa fa-list"></i> PROJETS</h1>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                     <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            {% include '_partials/messages_display.html' %}
                        </div>
                    </div>
                    <!-- /.row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <a href="#" class="btn btn-success"><i class="fa fa-file-excel-o fa-fw"></i> Exporter En Excel</a>
                                <a href="#" class="btn btn-danger"><i class="fa fa-file-pdf-o fa-fw"></i>  Exporter En PDF</a>
{#                                <button type="button" class="btn btn-success pull-right" style="font-size:1.8vmin;" data-toggle="modal" data-target="#ProjetModal" data-whatever="@mdo">#}
{#                                    <i class="fa fa-plus"> </i> Ajouter#}
{#                                </button>#}
                                </div>
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead class="text-center">
                                                <tr class="text-center">
                                                    <th>CATEGORIE</th>
                                                    <th>PROJET</th>
                                                    <th>CHEF</th>
                                                    <th>DEBUT</th>
                                                    <th>FIN</th>
                                                    <th>STATUS</th>
                                                    <th>ACTIONS</th>
                                                </tr>
                                            </thead>
                                            <tbody class="text-center">
                                                {% for projet in projets %}
                                                    <tr class="odd gradeX">
                                                        <td>{{ projet.categorie }}</td>
                                                        <td>({{ projet.accronyme }})</td>
                                                        <td>{{ projet.chef }}</td>
                                                        <td class="center">{{ projet.debut|date:'d/m/Y' }}</td>
                                                        <td class="center">{{ projet.fin|date:'d/m/Y' }}</td>
                                                        <td class="center">{{ projet.etat }}</td>
                                                        <td class="center">
                                                            <a href="{% url 'update_projet' projet.id %}" class="btn btn-info"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'delete_projet' projet.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                                            <a href="{% url 'clients:detail_proj' projet.id %}" class="btn btn-success"><i class="fa fa-chevron-right"></i></a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-8 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
{#                <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="ProjetModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#                <div class="modal-dialog modal-lg" role="document">#}
{#                        <form id="myform" method="post" enctype="multipart/form-data">#}
{#                            {% csrf_token %}#}
{#                            <div class="panel panel-green">#}
{#                            <div class="panel-heading">#}
{#                                <h4 class="modal-title" id="exampleModalLabel" style="font-weight:bold">FORMULAIRE PROJET</h4>#}
{#                                <button ID="btnAnnuler" type="button" data-dismiss="modal" class="btn btn-danger pull-right" style="font-size:1.8vmin;margin-top: -30px">#}
{#                                    <i class="fa fa-close"></i>#}
{#                                </button>#}
{#                            </div>#}
{#                            <div class="panel-body">#}
{#                                <div class="row">#}
{#                                    <div class="col-sm-12">#}
{#                                        <div class="row">#}
{#                                            <div class="col-sm-6">#}
{#                                                <div class="row">#}
{#                                                    <div class="col-sm-6">#}
{#                                                        <div class="form-group">#}
{#                                                            <label>CATEGORIE</label>#}
{#                                                            {% render_field form.categorie class="form-control" placeholder="CATEGORIE" %}#}
{#                                                            <input class="form-control" type="date" name="date" placeholder="date">#}
{#                                                        </div>#}
{#                                                    </div>#}
{#                                                    <div class="col-sm-6">#}
{#                                                        <div class="form-group">#}
{#                                                            <label>CLIENT</label>#}
{#                                                            {% render_field form.client class="form-control" placeholder="CLIENT" %}#}
{#                                                        </div>#}
{#                                                    </div>#}
{#                                                    <div class="col-lg-6">#}
{#                                                        <div class="form-group">#}
{#                                                            <label>DATE DEBUT</label>#}
{#                                                            <input class="form-control" type="number" name="plant_recus" placeholder="Nbre Total Plants Réçus">#}
{#                                                              {% render_field form.debut type="date" class="form-control" placeholder="DATE DEBUT" %}#}
{#                                                        </div>#}
{#                                                    </div>#}
{#                                                    <div class="col-lg-6">#}
{#                                                        <div class="form-group">#}
{#                                                            <label>DATE FIN</label>#}
{#                                                            <input class="form-control" type="number" name="plant_recus" placeholder="Nbre Total Plants Réçus">#}
{#                                                              {% render_field form.fin type="date" class="form-control" placeholder="DATE FIN" %}#}
{#                                                        </div>#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                                <div class="form-group">#}
{#                                                    <label>CHEF</label>#}
{#                                                            <input class="form-control" type="number" name="nb_plant_exitant" placeholder="Nbre Plants Existants">#}
{#                                                      {% render_field form.chef class="form-control" placeholder="CHEF PROJET" %}#}
{#                                                </div>#}
{#                                            </div>#}
{#                                            <div class="col-sm-6">#}
{#                                                <div class="form-group">#}
{#                                                    <label>SIGLE</label>#}
{#                                                    {% render_field form.accronyme class="form-control" placeholder="SIGLE" %}#}
{#                                                </div>#}
{#                                                <div class="form-group">#}
{#                                                    <label for="">TITRE</label>#}
{#                                                    {% render_field form.titre class="form-control" placeholder="TITRE" %}#}
{#                                                </div>#}
{#                                                <div class="form-group">#}
{#                                                    <label>ETAT</label>#}
{#                                                            <input class="form-control" type="number" name="plant_recus" placeholder="Nbre Total Plants Réçus">#}
{#                                                      {% render_field form.etat class="form-control" placeholder="ETAT" %}#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="panel-footer">#}
{#                                <input type="submit" name="btnValider" value="Valider" id="btnValider" class="btn btn-success btn-block btn_valider" style="font-size:1.7vmin;" />#}
{#                            </div>#}
{#                        </div>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
            </div>
            <!-- /#page-wrapper -->
        </div>
{% endblock %}